
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pseudoflows.ops.example.com
spec:
  group: ops.example.com
  scope: Namespaced
  names:
    kind: PseudoFlow
    plural: pseudoflows
    singular: pseudoflow
    shortNames: [pflow]
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                vars:
                  type: object
                  additionalProperties:
                    type: string
                steps:
                  type: array
                  items:
                    type: object
                    required: ["type"]
                    properties:
                      type:
                        type: string
                        enum: ["log","sleep","apply","delete","waitFor","setLabel","removeLabel","loop","parallel"]
                options:
                  type: object
                  properties:
                    timeoutSeconds:
                      type: integer
            status:
              type: object
